//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 7/17/2015 5:26:10 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace ExpandSortPOC.Models.v1
{
    public partial class ExpandSortEntities : DbContext
    {
        #region Constructors

        /// <summary>
        /// Initialize a new ExpandSortEntities object.
        /// </summary>
        public ExpandSortEntities() :
                base(@"name=ExpandSortConnectionString")
        {
            Configure();
        }

        /// <summary>
        /// Initializes a new ExpandSortEntities object using the connection string found in the 'ExpandSortEntities' section of the application configuration file.
        /// </summary>
        public ExpandSortEntities(string nameOrConnectionString) :
                base(nameOrConnectionString)
        {
            Configure();
        }

        private void Configure()
        {
            this.Configuration.AutoDetectChangesEnabled = true;
            this.Configuration.LazyLoadingEnabled = true;
            this.Configuration.ProxyCreationEnabled = true;
            this.Configuration.ValidateOnSaveEnabled = true;
        }

        #endregion

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            throw new UnintentionalCodeFirstException();
        }

    
        /// <summary>
        /// There are no comments for PocCntry in the schema.
        /// </summary>
        public virtual DbSet<PocCntry> PocCntry { get; set; }
    
        /// <summary>
        /// There are no comments for PocSubject in the schema.
        /// </summary>
        public virtual DbSet<PocSubject> PocSubject { get; set; }
    }
}
