//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 7/17/2015 5:26:10 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace ExpandSortPOC.Models.v1
{

    /// <summary>
    /// There are no comments for ExpandSortPOC.Models.v1.PocCntry in the schema.
    /// </summary>
    public partial class PocCntry    {

        public PocCntry()
        {
            OnCreated();
        }


        #region Properties
    
        /// <summary>
        /// There are no comments for CntryId in the schema.
        /// </summary>
        public virtual decimal CntryId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ClnclId in the schema.
        /// </summary>
        public virtual string ClnclId
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for PocSubject in the schema.
        /// </summary>
        public virtual ICollection<PocSubject> PocSubject
        {
            get;
            set;
        }

        #endregion
    
        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion
    }

}
